#!/usr/bin/env bash
# Wrapper for Microsoft Word via Bottles

EXE="WINWORD.EXE"

if [[ -n "$1" ]]; then
    WIN_PATH="Z:$(echo "$1" | sed 's|/|\\|g')"
    flatpak run --command=bottles-cli com.usebottles.bottles run -b msoffice -p "$EXE" -- "$WIN_PATH"
else
    flatpak run --command=bottles-cli com.usebottles.bottles run -b msoffice -p "$EXE"
fi
