#!/usr/bin/env bash

BOTTLE_DIR="$HOME/.var/app/com.usebottles.bottles/data/bottles/bottles/msoffice"
RUNNER_BIN="$HOME/.var/app/com.usebottles.bottles/data/bottles/runners/pol-8.2/bin/wine"
EXE_PATH='C:\Program Files\Microsoft Office\Office14\WINWORD.EXE'

if [[ -n "$1" ]]; then
    WIN_ARG="Z:$(echo "$1" | sed 's|/|\\|g')"
    flatpak run --command=bash com.usebottles.bottles -c \
        "WINEPREFIX='$BOTTLE_DIR' '$RUNNER_BIN' '$EXE_PATH' '$WIN_ARG'" 2>/dev/null &
else
    flatpak run --command=bash com.usebottles.bottles -c \
        "WINEPREFIX='$BOTTLE_DIR' '$RUNNER_BIN' '$EXE_PATH'" 2>/dev/null &
fi
disown
