Arch: win32
CompatData: ''
Custom_Path: false
DLL_Overrides:
    gdiplus: native,builtin
    riched20: native,builtin
DXVK: false
Environment: Custom
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- msxml6
- allfonts
- vcredist2019
- dotnet48
- riched20
Language: sys
LatencyFleX: false
NVAPI: false
Name: msoffice
Path: msoffice
Runner: pol-4.3
RunnerPath: ''
Sandbox: false
State: 0
Uninstallers: {}
VKD3D: false
Versioning: false
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
